Replugged update
OIRNOIR/oneko-animation pull request #1
Opened 2024-04-05 03:53 UTC by Saltssaumure

With Discord now having expiring image links, the preview image for the theme no longer loads. This PR updates the image link to a raw image in this repo.

Additional changes:
- Add release script to automatically bump version and create tag
- Update dependencies (including removing unused pkgs)
- Add GPL-3.0 license file hopefully in accordance with previous GPL license identifier

2024-04-05 05:29 UTC, OIRNOIR requested changes

2024-04-05 05:29 UTC, OIRNOIR commented on package.json
> -    "@types/node": "^20.10.5",
Why have you uninstalled these packages? They're for TS support.
Everything else looks good to me, it would still be great if you could explain though.

2024-04-05 05:34 UTC, Saltssaumure commented on package.json
> -    "@types/node": "^20.10.5",
Replugged no longer uses parcel (and by extensions node/types) for bundling css as of v4.7.x, so it's just no longer required

2024-04-05 06:35 UTC, OIRNOIR approved these changes

2024-04-05 06:35 UTC, merged

2024-04-06 00:35 UTC, Saltssaumure commented
When you get the chance to, could you please:
1. run `pnpm i && pnpm run release` to release a new version on github
2. post on #addon-reviews to get the theme updated on the Replugged store - if you're not able to do this for any reason, let me know and I can post for you.

2024-04-06 05:47 UTC, OIRNOIR commented
> When you get the chance to, could you please:
> 
>     1. run `pnpm i && pnpm run release` to release a new version on github
> 
>     2. post on #addon-reviews to get the theme updated on the Replugged store - if you're not able to do this for any reason, let me know and I can post for you.

1. That's not how I make a new release version in this repo but okay sure, I'll do it in a sec
2. Could you please post it for me? I'm not in the replugged server anymore.

2024-04-06 18:02 UTC, Saltssaumure commented
Store update complete 👍